Repository allegro/turnilo, pull requests merged in 2022-03, with the labels that each got.

#856 Scatterplot/ Fix missing x axis label
  src/client/visualizations/scatterplot/utils/get-plotting-data.mocha.ts
  src/client/visualizations/scatterplot/utils/get-plotting-data.ts
Labels: bug

#858 Bump react-syntax-highlighter to save on bundle size
  package-lock.json
  package.json
  src/client/index.d.ts
  src/client/modals/source-modal/source-modal.tsx
Labels: technical debt

#867 Missing rangeBand method
  src/client/components/bucket-marks/bucket-marks.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/bar/single-bar.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/bar/single-time-shift-bar.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/bar/stacked-bar.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/bar/stacked-time-shift-bar.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/foreground/highlight-modal.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/foreground/highlight-overlay.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/hover-tooltip/hover-tooltip.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/utils/x-scale.mocha.ts
  src/client/visualizations/bar-chart/improved-bar-chart/utils/x-scale.ts
Labels: bug

#869 Fix: Exclusion filter does not filter out 'null'
  src/client/components/selectable-string-filter-menu/string-values-list.tsx
  src/common/utils/formatter/formatter.ts
Labels: bug

#849 Split utils
  src/client/components/tabular-scroller/splits/flattened-split-columns.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/bar/single-bar.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/bar/single-time-shift-bar.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/bar/stacked-bar.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/bar/stacked-time-shift-bar.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/bars/bars-container.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/bars/bars.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/foreground/foreground.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/foreground/highlight-modal.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/foreground/highlight-overlay.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/hover-tooltip/hover-tooltip.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/hover-tooltip/tooltip-content.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/interactions/interaction-controller.tsx
  src/client/visualizations/bar-chart/improved-bar-chart/utils/bar-chart-model.ts
  src/client/visualizations/bar-chart/improved-bar-chart/utils/transpose-dataset.ts
  src/client/visualizations/bar-chart/improved-bar-chart/utils/x-domain.mocha.ts
  src/client/visualizations/bar-chart/improved-bar-chart/utils/x-domain.ts
  src/client/visualizations/bar-chart/improved-bar-chart/utils/x-scale.mocha.ts
  src/client/visualizations/bar-chart/improved-bar-chart/utils/x-scale.ts
  src/client/visualizations/line-chart/charts/charts-per-series/series-chart.tsx
  src/client/visualizations/line-chart/charts/charts-per-series/series-hover-content.tsx
  src/client/visualizations/line-chart/charts/charts-per-split/label.tsx
  src/client/visualizations/line-chart/charts/charts-per-split/nominal-value-key.ts
  src/client/visualizations/line-chart/charts/charts-per-split/split-chart.tsx
  src/client/visualizations/line-chart/interactions/find-closest-datum.ts
  src/client/visualizations/line-chart/legend/split-legend.tsx
  src/client/visualizations/line-chart/utils/x-scale.ts
  src/client/visualizations/scatterplot/scatterplot.tsx
  src/client/visualizations/scatterplot/tooltip.tsx
  src/common/models/split/split.mocha.ts
  src/common/models/split/split.ts
Labels: technical debt

#885 Show NoData card on BarChart when no split datums came from Druid
  src/client/visualizations/bar-chart/improved-bar-chart/bar-chart.tsx
Labels: bug

#887 Typescript fixes in package.json
  .github/workflows/deploy-branch.yml
  .github/workflows/deploy-master.yml
  cypress/index.d.ts
  cypress/integration/split-tile.spec.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
  src/common/models/time-tag/time-tag.mocha.ts
  src/common/models/time-tag/time-tag.ts
  src/server/www.ts
  tsconfig.json
Labels: bug, technical debt

#889 Memoize Viz Chunk so Suspense won't get new Promise every time.
  src/client/views/cube-view/cube-view.tsx
  src/client/visualizations/index.ts
Labels: bug
